config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('photolog/', include('photolog.urls')),
    path('stocks/', include('stockrankings.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import comment_create, create, list, detail, update, delete
app_name = 'posts'

urlpatterns = [
    path('list/', list, name="list"),
    path('create/', create, name="create"),
    path('<int:id>/', detail, name="detail"),
    path('<int:id>/update/', update, name="update"),
    path('<int:id>/delete/', delete, name="delete"),
    path('<int:id>/comment_create/', comment_create, name="comment_create"),
]

posts/models.py
from os import terminal_size
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(
        verbose_name='제목',
        max_length=80,
    )

    content = models.TextField(
        verbose_name='내용'
    )

    created_at = models.DateTimeField(
        verbose_name='작성일'
    )

    created_by = models.CharField(
        verbose_name='작성자',
        max_length=100
    )

    is_view = models.BooleanField(
        verbose_name='공개 여부',
        default=True
    )


class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)

posts/views.py
from operator import pos
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post, Comment
import datetime
from  django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.

def delete(request, id):
    context = {}
    post = Post.objects.get(id=id)

    if request.method == 'POST':
        
        post.delete()
        return redirect('posts:list')
    else:
        context.update(post=post)
        return render(request, 'posts/confirm_delete.html', context)


def update(request, id):
    #메소드가 POST인경우
    if request.method == 'POST':
    #1-1. 사용자에게 전달받은 값으로 데이터 조회
        post = Post.objects.get(id=id)

    #1-2. 사용자에게 전달받은 값 확인
        title = request.POST['title']
        content = request.POST['content']
        created_by = request.POST['created_by']

    #1-3. 데이터수정
        post.title = title
        post.content = content
        post.created_by = created_by
        post.save()

    #1-4 응답
        return redirect('posts:detail', post.id)
    #2 메소드가 GET인경우
    #
    elif request.method == "GET":
    #2-1 사용자에게 전달받은 값으로 데이터 조회
        post = Post.objects.get(id=id)
        context = {'post': post}
    #2-2폼 응답
        return render(request, "posts/form.html", context)

    

def detail(request, id):
    #1. 사용자에게 전달받은 값으로 데이터 조회
    post = Post.objects.get(id=id)
    comment_list = Comment.objects.filter(post=post)
    context = {"post": post, 'comment_list': comment_list}
    #2. 응답
    return render(request, 'posts/detail.html', context)

# def new(request):
#     # 게시글 작성 HTML 응답
#     return render(request, 'form.html')

@login_required
def create(request):
    if request.method == 'POST':
    #1. 클라이언트에게 받은 값 변수 생성
        input_title = request.POST['title']
        input_content = request.POST['content']
        input_created_by = request.POST['created_by']
        #2. 게시글(post) 생성
        post = Post.objects.create(
            title = input_title,
            content=input_content,
            created_at=datetime.datetime.now(),
            created_by=input_created_by,
        )
        #3. 응답
        #return render(request,'form.html')
        return redirect("posts:detail", post.id)
        
    else:
        return render(request, 'posts/form.html')


def list(request):
    #1 게시글 전체조회
    post_all = Post.objects.all()
    context = {'post_all': post_all}
    #2. 게시글 전체, HTML응답
    return render(request, 'posts/list.html', context)

@login_required
def comment_create(request, id):
    post = get_object_or_404(Post, id=id)
    content = request.POST.get('content')
    Comment.objects.create(content=content, post=post)
    return redirect('posts:detail', post.id)

templates/posts/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
주식매매일지 삭제
{% endblock %}

{% block content %}
    <a href="{% url 'posts:list' %}">주식 매매일지 보기</a>
    <!-- 폼생성 input 제목, 내용, 작성자 -->
    <form action="" method="POST">
        {% csrf_token %}
        {% include 'posts/post_card.html' %}
        <div>
            <p>위 글을 삭제하시겠습니까?</p>
            <p>삭제된 글은 복원할 수 없습니다.</p>
        </div>
        <input type="submit" value="삭제하기">
        <a href="{{ request.META.HTTP_REFERER }}">뒤로가기</a>
    </form>

{% endblock %}

templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
게시글 내용
{% endblock %}

{% block content %}
    <h1>주식매매일지</h1>
    {% include  'posts/post_card.html' %}
    <button><a href="{% url 'posts:list' %}">주식매매일지 목록보기 </a></button>
    <button><a href="{% url 'posts:update' post.id %}">수정하기 </a></button>
    <button><a href="{% url 'posts:delete' post.id %}">삭제하기 </a></button>
    <hr>
   
    <form action="{% url 'posts:comment_create' post.id %}" method="POST">
    {% csrf_token %}
    <input type="text" name="content">
    <input type="submit" value="댓글작성하기">
    </form>
    {% for comment in comment_list %}
    <p>{{ comment.content }} | {{ comment.created_at }}</p>
    {% empty %}
    <p>댓글이 없습니다.</p>
    {% endfor %}
{% endblock %}

templates/posts/form.html
{% extends 'base.html' %}

{% block title %}
주식 매매일지 작성
{% endblock %}


{% block content %}
<a href="{% url 'posts:list' %}">주식매매일지 보기</a>
<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label>제목</label>
        <input type="text" name="title" value="{{post.title}}">
    </div>

    <div>
        <label>내용</label>
        <textarea name="content">{{post.content}}</textarea>
    </div>

    <div>
        <label>작성자</label>
        <input type="text" name="created_by" value="{{post.created_by}}">
    </div>

    <div>
        <input type="submit" value="게시글 작성">
    </div>
</form>

{% endblock %}

templates/posts/list.html
{% extends 'base.html' %}

{% block title %}
공지사항
{% endblock %}

{% block content %}

<h1>투자의구루 게시판</h1>
<a href="{% url 'posts:create' %}" class="btn btn-primary">글쓰기</a>
<table class="table table-striped table-hover">
    <tr>
        <th>번호</th> <!-- th*4 그리고 tab -->     <!-- tr>th*3 그리고 tab -->
        <th>제목</th>
        <th>작성자</th>
        <th>작성일</th>
    </tr>
    {% for post in post_all %}
    <tr>
        <td>{{ post.id }}</td>
        <td><a href="{% url 'posts:detail' post.id %}">{{post.title}}</td>
        <td>{{post.created_by}}</td>
        <td>{{post.created_at}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

templates/posts/post_card.html
id : {{post.id}}<br>
title : {{post.title}}<br>
content : {{post.content}}<br><br>