config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('photolog/', include('photolog.urls')),
    path('stocks/', include('stockrankings.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photolog/urls.py
from django.urls import path
from .views import create, list

app_name = 'photolog'

urlpatterns = [
    path('create/', create , name="create"),
    path('list/', list , name="list"),
]

posts/urls.py
from django.urls import path
from .views import comment_create, create, list, detail, update, delete
app_name = 'posts'

urlpatterns = [
    path('list/', list, name="list"),
    path('create/', create, name="create"),
    path('<int:id>/', detail, name="detail"),
    path('<int:id>/update/', update, name="update"),
    path('<int:id>/delete/', delete, name="delete"),
    path('<int:id>/comment_create/', comment_create, name="comment_create"),
]

photolog/models.py
from django.db import models

# Create your models here.
class Photolog(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='image/')
    description = models.TextField(max_length=1000)

photolog/views.py
from django.shortcuts import render, redirect
from .models import Photolog

# Create your views here.

def list(request):
    Photolog_all = Photolog.objects.all()
    context = {"photolog_all" : Photolog_all}
    return render(request, 'photolog/list.html', context)

def create(request):
    if request.method == 'POST':
        #클라이언트 데이터 수신
        input_title = request.POST['title']
        input_image = request.FILES['image']
        input_description = request.POST['description']
        #모델 생성
        Photolog.objects.create(title=input_title, image=input_image, description=input_description)
        #응답
        return redirect('photolog:list')

    else:
        return render(request, 'photolog/form.html')

templates/photolog/form.html
{% extends 'base.html' %}

{% block title %}
수익률 인증 게시판
{% endblock %}

{% block content %}
<form action="", method="POST" enctype="multipart/form-data">
 {% csrf_token %}
<label for="title">제목</label>
<input type="text" name="title" id="title"><br>
<label for="description">종목 구성 설명</label>
<input type="text" name="description" id="description"><br>
<label>수익률 인증하기</label>
<input type="file" name="image"><br>
<input type="submit" value="이미지첨부">

</form>
{% endblock  %}

templates/photolog/list.html
{% extends 'base.html' %}

{% block title %}
이미지리스트
{% endblock %}

{% block content %}
<h1>주식 계좌 인증</h1>
<a href="{% url 'photolog:create' %}">이미지 업로드하기</a><br>
{% for photolog in photolog_all %}
<p>제목{{ photolog.title}}</p>
<p>종목구성 {{ photolog.description}}</p>
{{ photolog.image}}<br>
<img src="{{ photolog.image.url }}"><br><br><br>

{% endfor %}
{% endblock %}