accounts/urls.py
from django.urls import path
from .views import signup, login, logout

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name="signup"),
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('photolog/', include('photolog.urls')),
    path('stocks/', include('stockrankings.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from .views import home

app_name = 'homepage'

urlpatterns = [
    path('', home, name="home"),
]

photolog/urls.py
from django.urls import path
from .views import create, list

app_name = 'photolog'

urlpatterns = [
    path('create/', create , name="create"),
    path('list/', list , name="list"),
]

posts/urls.py
from django.urls import path
from .views import comment_create, create, list, detail, update, delete
app_name = 'posts'

urlpatterns = [
    path('list/', list, name="list"),
    path('create/', create, name="create"),
    path('<int:id>/', detail, name="detail"),
    path('<int:id>/update/', update, name="update"),
    path('<int:id>/delete/', delete, name="delete"),
    path('<int:id>/comment_create/', comment_create, name="comment_create"),
]

stockrankings/urls.py
from django.urls import path
from .views import ranking, tenbaggers, detail, comment_create, test

app_name = 'stockrankings'

urlpatterns = [
    path('ranking/', ranking, name="ranking"),
    path('tenbaggers/', tenbaggers, name="tenbaggers"),
    # path('', search, name="search"),
    path('<str:ticker>/', detail, name="detail"),
    path('<str:ticker>/comment_create/', comment_create, name="comment_create"),
    path('testhtml', test, name="test"),
    
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}| 투자의구루 {% endblock %}</title>

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
        <script>
            $(document).ready(function() {
                $('#rank').DataTable();
            } );
        </script>
        
        <link rel="stylesheet" href="{% static 'css/main.css' %}?after=2">

        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF"
            crossorigin="anonymous">

    </head>

    <body>
      <h1 id="clock"></h1>
        <header>
            <div>
                {% if user.is_authenticated %}
                    <button>
                        <a href="{% url 'accounts:logout' %}">Logout</a>
                    </button>
                {% else %}
                    <button>
                        <a href="{% url 'accounts:login' %}">Login</a>
                    </button>
                    <button>
                        <a href="{% url 'accounts:signup' %}">signup</a>
                    </button>
                {% endif %}
            </div>

            <div>
                <center>
                    <a href="{% url 'homepage:home' %}">
                        <img src="{% static 'image/logo.png' %}" alt="투자의구루 로고" class="logo rounded">
                    </a>
                </center>
                <br>
            </div>
        </header>
    </header>

    <div class="text-center">
      <h1>투자의구루</h1>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a href="{% url 'stockrankings:ranking' %}" class="nav-link active" aria-current="page"
              >Stock Ranking</a
            >
          </li>

          <li class="nav-item">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'stockrankings:tenbaggers' %}"
              >10 Baggers finder</a
            >
          </li>

          <li class="nav-item">
            <a
              class="nav-link active"
              aria-current="page"
              href="{% url 'posts:list' %}"
              >게시글 남기기</a
            >
          </li>
          <li class="nav-item">
            <a href="{% url 'photolog:list' %}" class="nav-link active" aria-current="page"
              >Instockgram</a
            >
          </li>
        </ul>
      </div>
    </nav>
    <br><br><br>
     {% comment %} <form action="{% url 'stockrankings:search' %}" method="post">
            {% csrf_token %}
            <center>
                <input
                    class="search_bar"
                    type="search"
                    placeholder="Search"
                    aria-label="Search"
                    name="q"
                    value="{{q}}">
            </center>
        </form> {% endcomment %}
    
    {% block content %}{% endblock %}
    <script src={% static 'js/clock.js' %}></script>
  </body>
</html>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>홈페이지 | 투자의 구루</title>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF"
      crossorigin="anonymous"
    />
  </head>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
      홈페이지 | 투자의 구루
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    <center>
      <a href="{% url 'homepage:home' %}">
          <img class="logo" src="{% static 'image/logo.png' %}" alt="투자의구루 로고">
      </a>
    </center>

</head>
<br><br><br>

<body>

<a href="{% url 'stockrankings:ranking' %}">Stock Ranking</a>
<br>
<a href="{% url 'stockrankings:tenbaggers' %}">10 baggers</a>
<br>
<a href="{% url 'posts:list' %}">Notice</a>    
<br>
<a href="{% url 'photolog:list' %}">Instockgram</a>
<br>
<a href="{% url 'stockrankings:test' %}">test html</a>
<br>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>


</body>

</html>